package com.ajwalker.utility.Enum.embezzlement;

public enum EEmbezzlementType {
    ELECTRONICDEVICES,
    OFFICEEQUIPMENT,
    VEHICLESANDTRANSPORTATION,
    PROTECTIVEGEAR,
    TECHNICALEQUIPMENT,
    STATIONERYANDOFFICESUPPLIES,
    COMPANYCARDS,
    CLOTHINGANDUNIFORMS
}
